### ISSUE TITLE
Feature: `attribution-fallback` config

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/pizza-cli#116]
### Suggested solution

There are cases where there may not be a codeowner that is derived off the range of commits that are being inspected. We should include a `attribution-fallback` key in the config:

```yaml
attribution:
  jpmcb:
    - john@opensauced.pizza
  brandonroberts:
    - brandon@opensauced.pizza

attribution-fallback:
  - open-sauced/engineering
```

This filed in the config could then be used to attribution files that don't have an active attribution.

**_Example_**: the codeowners generation can create valid codeowners without attributions if there are no commits in the time range for certain files:

```codeowners
/file/with/codeowner @jpmcb
/file/without/codeowner
```

With this change, it should generate:

```codeowners
/file/with/codeowner @jpmcb
/file/without/codeowner @open-sauced/engineering
```
