### ISSUE TITLE
Feature: Feedback - Offboarding experience with `pizza clean` or `pizza offboard`

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/pizza-cli#117]
### Suggested solution

Some early feedback we've gotten has been around the "offboarding experience" as it relates to GitHub resources and generating codeowners files.

**_Scenario_**: let's say an engineering team on GitHub maintains the following sauced config file:

```yaml
attribution:
  open-sauced/engineering:
    - john@email.domain
    - brandon@email.domain
```

Where commits authored by `john` and `brandon` get attributed to the `@open-sauced/engineering` GitHub team in the `CODEOWNERS` file.

Let's say that someone leaves the company and the file gets updated to:

```yaml
attribution:
  open-sauced/engineering:
    - brandon@email.domain
```

Now, those (and future) commits authored by `john` won't appear as part of the `@open-sauced/engineering` team attribution in the `CODEOWNERS`.

_But_, there still may be issues assigned to `john` on GitHub or other resources (like the GitHub team) that `john` needs to get offboarded from. A subsequent `pizza clean john@email.domain` or `pizza offboard ...` command could be used to remove that user from those resources on GitHub.

---

We'd also want to think through this experience with users who are _not_ operating on GitHub since the `pizza generate codeowners` command attempts to be as agnostic as possible.
