### ISSUE TITLE
Feature: enable npm caching

### ISSUE THREAD

**Issue by jpmcb** [open-sauced/pizza-cli#121]
### Suggested solution

In an effort to speed up builds and CI/CD, we should take advantage of the caching capabilities in the `setup-node` action we use during release:

```yaml
- uses: actions/setup-node@v4
  with:
    node-version: 18
    cache: 'npm'
```
