### ISSUE TITLE
Feature: Native Bitbucket Integration

### ISSUE THREAD

**Issue by udaypatel1** [open-sauced/pizza-cli#221]
### Suggested solution

In it's current state, the `.sauced.yaml` config file natively supports Github usernames and teams.

For the use case of my team, we use Bitbucket as our SCM and would appreciate native support for Bitbucket specific features as we don't have a notion of "Github Teams", as an example.

In general, it would be amazing if the config file (among other parts of the Pizza CLI) could support specificities in other SCM platforms, exposing it's capabilities to a larger audience.

Thanks! 😁🚀

**Comment by jpmcb** [comment]
Hi @udaypatel1 - thanks for opening the issue! We currently don't have any plans to open up support in the Pizza CLI to other git providers like bitbucket or gitlab.

But we're very interested to hear how this would integrate with bitbucket. Can you give me some examples of how you imagine this working?

Is this the feature you'd want to use? https://support.atlassian.com/bitbucket-cloud/docs/set-up-and-use-code-owners/ To get something like this to work (where it'd be straight emails associated to files), you'd simply want to set up your `.sauced.yaml` to be a straight mapping of emails to email keys like so:

```yaml
attribution:
  john@opensauced.pizza:
    - john@opensauced.pizza
    - johns-other-email@opensauced.pizza
  other-opensauced-dev@opensauced.pizza:
    - other-opensauced-dev@opensauced.pizza
```
